baseURL = "https://www.roundtabledev.com/"
languageCode = "en-us"
title = "Roundtable Development"
theme = "PaperMod"
googleAnalytics = "UA-XXXXXX-X"

[params.label]
text ="Roundtable Development"

[params.profileMode]
enabled = false
title = "Roundtable Development"
imageUrl = "/images/logo.png"
imageTitle = "Roundtable Dev"
imageWidth = 300
imageHeight = 230

[params.homeInfoParams]
Title = "Hi there"
Content = """
Welcome to my blog.

It is a blog.
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[deployment]

[[deployment.targets]]
name="main-deploy"
URL="s3://www.roundtabledev.com?region=us-east-1"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
