baseURL = "https://www.roundtabledev.com/"
languageCode = "en-us"
title = "Roundtable Development"
theme = "PaperMod"
copyright = "&copy; 2021 Roundtable Development, LLC"

[params.label]
text ="Roundtable Development"

[params.homeInfoParams]
Title = "We build good things with code"
Content = """
Custom software development that you're actually excited to
keep doing.
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/roundtableDevelopment"

[deployment]

[[deployment.targets]]
name="main-deploy"
URL="s3://www.roundtabledev.com?region=us-east-1"
cloudFrontDistributionID = "E13KRC9PPYCBL"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
